@isTest
public class UserDaoTest {
    
    static testMethod void myUnitTest() {
        
        /*
        
        //テスト用のデータ作成
        User__c us1 = new User__c(
            Name='中山テスト１',Number__c='00001', Password__c = 'test001', Mail__c = 'test01@test.com');
        User__c us2 = new User__c(
            Name='中山テスト２',Number__c='00002', Password__c = 'test002', Mail__c = 'test02@test.com');


        list<User__c> insUserList =
            new List<User__c>();
        insUserList.add(us1);
        insUserList.add(us2);
        
        insert insUserList; //データ挿入
        
        //テストを行いたいクラスを生成
        list<User__c> qUserList = 
            UserDao.getUserDate(System.today());
        
        for(User__c U : qUserList) {
            system.debug('■■■ユーザの名前：' + U.Name);   
        }
        
        system.assertEquals(1, qUserList.size());
        
        */
        
        
    }
}